Repository nspcc-dev/neofs-api, pull requests merged in 2020-10, with the labels that each got.

#76 Add clarification for BearerToken.body.owner_id
  acl/types.proto
Labels: bug, documentation

#77 Add more well-known attributes
  container/types.proto
  object/types.proto
Labels: documentation, enhancement

#80 Clarify well-known object filters `parent` and `childfree`
  object/service.proto
  proto-docs/object.md
Labels: bug
