Repository nspcc-dev/neofs-api, pull requests merged in 2020-09, with the labels that each got.

#58 Simplify Placement Policy
  netmap/types.proto
  object/service.proto
  proto-docs/netmap.md
Labels: discussion, enhancement

#64 Add Version field to eECL Table and fix naming issues
  acl/types.proto
  proto-docs/acl.md
Labels: enhancement

#65 Add LocalNodeInfo request
  netmap/service.proto
  proto-docs/netmap.md
Labels: enhancement

#67 Use tuple of full header and signature at object head response body
  object/service.proto
Labels: bug

#68 Add SAME|DISTINCT selector clause
  netmap/types.proto
  proto-docs/netmap.md
Labels: bug, enhancement

#69 Add simple DCO check
  .github/workflows/dco.yml
Labels: enhancement

#70 Fix wrong DCO action config
  .github/workflows/dco.yml
Labels: bug

#71 Add GH Action for protobuf linter
  .github/workflows/buf.yml
Labels: enhancement
