Repository nspcc-dev/neofs-api, pull requests merged in 2020-04, with the labels that each got.

#1 docs: Update readme file for public release
  README.md
Labels: documentation

#4 docs: Add changelog file
  CHANGELOG.md
Labels: documentation

#8 Add gRPC method to change current node state
  Makefile
  proto-docs/object.md
  proto-docs/state.md
  state/service.proto
Labels: documentation, enhancement

#12 Disable stringer method for CreationPoint
  object/types.proto
  proto-docs/service.md
Labels: enhancement
