Repository nspcc-dev/neofs-api, pull requests merged in 2021-02, with the labels that each got.

#125 object: Define STRING_NOT_EQUAL value in MatchType enum
  object/types.proto
Labels: enhancement

#128 object: Add json_name tags to fields of SearchRequest.Body.Filter
  object/service.proto
Labels: enhancement

#132 Add release instructions
  doc/release_instructions.md
Labels: documentation, enhancement

#136 Same expiration epoch value in tombstone body and header
  tombstone/types.proto
Labels: bug

#137 Clarify empty search filter behaviour
  object/service.proto
Labels: bug, documentation
